### ISSUE TITLE
question about how the vehicle was set up to get back to the depot.

### ISSUE THREAD

**Issue by moonlioght** [ruthmair/vrp#1]
hello,
Thank you very much for your detailed notes. But currently I encountered a problem when implementing CVRP. If it is convenient, I hope to get your help.

The CVRP I hope to implement is like this:
1）There are n customer nodes, which are 1... n: The fixed depot node is 0.
2）The demand of each customer node is q_i
3）There is only one vehicle with a capacity limit Q, but every time the capacity of the vehicle is used up, it will be returned to the depot and refilled.

```
def solve_cvrp_bigM(V, N, E, d, Q, q, time_limit=None):
    # V：include depot node 0  N：all customer node  E：all edges
    # d: cost q:demand Q:capacity limitation for the vehicle
    model = gp.Model("CVRP")
    
    # edge x 0-1 variable
    x = {e: model.addVar(vtype=GRB.BINARY, name="x[{}]".format(e) ) for e in E}
    # Vehicle's serviced capacity variable for customer node i 
    u = model.addVars(V,vtype=GRB.CONTINUOUS)
    u[0] = 0  # for depot 0
    model.update()

    ### objective
    model.setObjective(gp.quicksum(d[e] * x[e] for e in E), GRB.MINIMIZE)

    ### 
    # in and out once and only once
    model.addConstrs(gp.quicksum(x[i,j] for j in V if j != i) == 1 for i in N)
    model.addConstrs(gp.quicksum(x[i,j] for i in V if i != j) == 1 for j in N)
    # bigM model
    model.addConstrs( ( (u[i] + q[j]) <= (u[j] + Q*(1-x[i,j])) ) for i in V for j in N if i!=j)
    model.addConstrs( ( (u[i] + q[j])
                      >= ( u[j] - (Q - q[i] - q[j])*(1-x[i,j]) ) ) for i in V for j in N if i!=j)
    # model.Params.outputFlag = False
    # model.Params.threads = 1 
    model.Params.MIPGap = 0.1
    if time_limit is not None:
        model.Params.timeLimit = time_limit
    model.optimize()
    if model.SolCount <= 0:
        return None, None
    x_sol = {e: round(x[e].x) for e in x}
    return (model.ObjVal), x_sol
```
The CVRP of only one vehicle that has been implemented so far is as above, but I don’t know how to make this vehicle refill every time it returns to the depot to continue serving customer nodes.

**Comment by moonlioght** [comment]
I got it!

**Comment by ruthmair** [comment]
This is interesting. In principle, I would argue that the variant of a single vehicle going back to the depot refilling is not different from the standard variant with multiple vehicles since there is no time dimension in the CVRP.
I am just curious, is there some additional constraint in your variant to requires changes to the CVRP formulation?
How did you fix your issue?
